//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurlOakMovers.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer()
        {
            this.workorders = new HashSet<workorder>();
        }
        [Key]
        [DisplayName("First Name")]
        public int custid { get; set; }
        [DisplayName("First Name")]
        public string custname { get; set; }
        [DisplayName("Last Name")]
        public string custlname { get; set; }
        [DisplayName("Address")]
        public string custaddress { get; set; }
        [DisplayName("City")]
        public string custcity { get; set; }
        [DisplayName("Postal Code")]
        public string custpostal { get; set; }
        [DisplayName("Email")]
        public string custemail { get; set; }
        [DisplayName("Primary Number")]
        public string custphone { get; set; }
        [DisplayName("Secondary Number")]
        public string custcellphone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<workorder> workorders { get; set; }
    }
}
