//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurlOakMovers.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer()
        {
            this.workorders = new HashSet<workorder>();
        }
        [Key]
        public int custid { get; set; }
        public string custname { get; set; }
        public string custlname { get; set; }
        public string custaddress { get; set; }
        public string custcity { get; set; }
        public string custpostal { get; set; }
        public string custemail { get; set; }
        public string custphone { get; set; }
        public string custcellphone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<workorder> workorders { get; set; }
    }
}
